baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Yet another static website'
theme = "etch"

[params]
	description = "Notes about iOS development"
	copyright = "Copyright Â© 2021 Marco Meschini"
	dark = "auto"
	highlight = true
	